O_POSITIVE = 'O+'
O_NEGATIVE = 'O-'
A_POSITIVE = 'A+'
A_NEGATIVE = 'A-'
B_POSITIVE = 'B+'
B_NEGATIVE = 'B-'
AB_POSITIVE = 'AB+'
AB_NEGATIVE = 'AB-'

EARTH_RADIUS = 6371

BLOOD_GROUP_WEIGHTAGE = 5
LOCATION_WEIGHTAGE = 5